jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash) -t e4ea82dc-865d-415d-a37f-a5877472c4bc
